title: JavaFAQ
lang: en
description: a collection of frequently asked questions on various java topics.

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
    with_frontmatter: true

scss: |
  .container{background:#fff}
